name: gapaid
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - pip=25.2
  - python=3.9.23
  - pip:
      - cffi==2.0.0
      - darkdetect==0.8.0
      - numpy==2.0.2
      - pycparser==2.23
      - pyfastx==2.2.0
      - pyqt-fluent-widgets==1.8.7
      - pyqt5==5.15.11
      - pyqt5-frameless-window==0.7.3
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pyqtgraph==0.13.7
      - xcffib==1.5.0