name: gapaid
channels:
  - defaults
dependencies:
  - pip=25.2
  - python=3.9.23
  - pip:
      - darkdetect==0.8.0
      - numpy==2.0.2
      - pyfastx==2.2.0
      - pyqt-fluent-widgets==1.8.7
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pyqtgraph==0.13.7
